### ISSUE TITLE
[1.12] Reverting recipes not working

### ISSUE THREAD

**Issue by dimensionsintime** [Volen1/Compressed#1]
In 1.12 I can compress cobblestone just fine, but is there supposed to be a way to revert back to the lower compressions?

**Comment by Volen1** [comment]
There definitely is, I completely forgot to add that in. I'll have it fixed next update.

**Comment by Volen1** [comment]
Please make sure you post this on the correct repository next time!

**Comment by dimensionsintime** [comment]
What repo should I post to?

**Comment by Volen1** [comment]
The CompressedRewrite one. On the Curse Forge project page, that one is directly linked to for both Source, and Issues.

https://github.com/Volen1/CompressedRewrite

**Comment by dimensionsintime** [comment]
Pretty sure I clicked source on curseforge to get here, but okay, sorry for the confusion.
